### ISSUE TITLE
Save to a Stream error

### ISSUE THREAD

**Issue by siten** [aspose-words/Aspose.Words-for-C#49]
doc->Save(std::cout, Aspose::Words::SaveFormat::Text);

Assertion failed: m_mode == SmartPtrMode::Weak, file packages\codeporting.native.cs2cpp.api.21.11.0\build\native\include\system\smart_ptr.h, line 1244

Another question is, for very large word files, are there any interfaces such as callbacks or iterators that can receive the converted results part by part?

**Comment by btolfa** [comment]
Hi @siten,

> Assertion failed: m_mode == SmartPtrMode::Weak, file packages\codeporting.native.cs2cpp.api.21.11.0\build\native\include\system\smart_ptr.h, line 1244

We can't reproduce the issue. Can you give a complete example with the error or a word file that causes an issue?

**Comment by btolfa** [comment]
Regarding the second question
> Another question is, for very large word files, are there any interfaces such as callbacks or iterators that can receive the converted results part by part?

I'm afraid Aspose.Words for C++  doesn't support such a use case, at least for the text format.

We have the following API - [IPageLayoutCallback](https://apireference.aspose.com/words/cpp/class/aspose.words.layout.i_page_layout_callback). It allows to stop converstation and save document intermidate results.
The similar callback available for HTML - [IDocumentLoadingCallback](https://apireference.aspose.com/words/cpp/class/aspose.words.saving.i_document_part_saving_callback)

Starting from 21.12 version we will support similar callback for document loading, but only for docx like formats - [IDocumentLoadingCallback](https://apireference.aspose.com/words/cpp/class/aspose.words.loading.i_document_loading_callback)

**Comment by siten** [comment]
> Regarding the second question
> 
> > Another question is, for very large word files, are there any interfaces such as callbacks or iterators that can receive the converted results part by part?
> 
> I'm afraid Aspose.Words for C++ doesn't support such a use case, at least for the text format.
> 
> We have the following API - [IPageLayoutCallback](https://apireference.aspose.com/words/cpp/class/aspose.words.layout.i_page_layout_callback). It allows to stop converstation and save document intermidate results. The similar callback available for HTML - [IDocumentLoadingCallback](https://apireference.aspose.com/words/cpp/class/aspose.words.saving.i_document_part_saving_callback)
> 
> Starting from 21.12 version we will support similar callback for document loading, but only for docx like formats - [IDocumentLoadingCallback](https://apireference.aspose.com/words/cpp/class/aspose.words.loading.i_document_loading_callback)

Thank you for your answer
